language: go

sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker-compose.test.yml up -d

script: 
  - sudo go test ./...

after_script:
  - docker-compose -f docker-compose.test.yml down