language: go

sudo: required

branches:
  only:
    - master

services:
  - docker

before_script:
  - docker-compose -f docker-compose.test.yml up -d

script: 
  - chmod 777 . # allow current dir to be executed, written to, anything
  - GO_EXECUTABLE_PATH=$(which go)
  - echo $GO_EXECUTABLE_PATH
  - sudo $GO_EXECUTABLE_PATH test ./...

after_script:
  - docker-compose -f docker-compose.test.yml down