language: go

services:
  - docker

before_script:
  - docker-compose -f docker-compose.test.yml up -d

script: 
  - go test ./...

after_script:
  - docker-compose -f docker-compose.test.yml down