language: go

sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker-compose.test.yml up -d

script: 
  - chmod 777 . # allow current dir to be executed
  - go test ./...

after_script:
  - docker-compose -f docker-compose.test.yml down